### ISSUE TITLE
TaskCanceledException

### ISSUE THREAD

**Issue by marioescuder82** [OpenKuka/KukavarClient#2]
Hi!

I'm using KukavarClient and KUKAVARPROXY in the same computer.

Every few seconds, Kukavarclient catch a TaskCanceledException (log shows "Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll") and after that, the client reconnects.

Any idea?

Thanks!

**Comment by marioescuder82** [comment]
Sorry, it was my fault, now it works fine.

Thanks!

**Comment by lionpeloux** [comment]
Great. I'm glad you made it !
